20-storybook: Добавил сторибук и конфигурацию для него
studtool/frontend pull request #23
Opened 2019-05-12 17:39 UTC by SinimaWath

1. Сторибук
2. Несколько историй для примера
3. Чуть-чуть поменял обращение к пропсам в SignUpForm

2019-05-13 12:58 UTC, nikitarub commented
тест на [тревисе](https://travis-ci.com/studtool/frontend/builds/111494326) обвалился

обнови снепшот
запуск теста `npm test`

2019-05-13 21:47 UTC, SinimaWath commented
Добавил husky

2019-05-17 13:09 UTC, nikitarub requested changes
Добавь ещё линтер в препуш плез

2019-05-17 13:09 UTC, nikitarub commented on package.json
> +      "pre-push": "npm test"
Можешь пожалуйста ещё линт прикрутить к нему (npm run lint)

2019-05-18 13:33 UTC, merged